# Generated by Django 3.1.5 on 2021-02-09 22:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210209_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Phone of the employee.', max_length=31)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='details',
        ),
    ]
