# Generated by Django 3.1.5 on 2021-02-11 00:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_customer_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='post',
            name='Employee_phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Employee phone.', max_length=31),
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='customer_name',
            field=models.CharField(default='Cutomer name', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='customer_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Customer phone', max_length=31),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, '    open'), (2, 'pending'), (3, 'closed')], default=1),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
