# Generated by Django 3.1.5 on 2021-02-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
