# Generated by Django 3.1.5 on 2021-02-18 00:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210211_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment',
            field=models.IntegerField(choices=[(4, ' Cash'), (5, 'Card'), (6, 'Transfer')], default=4),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='$', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='tax',
            field=models.CharField(default='GSD', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Employee_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
