# Generated by Django 3.1.5 on 2021-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210218_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
