# Generated by Django 3.1.5 on 2021-02-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_tax_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tax_result',
        ),
        migrations.AlterField(
            model_name='post',
            name='tax',
            field=models.IntegerField(choices=[(7, ' Yes'), (8, 'No')], default=7),
        ),
    ]
