# Generated by Django 3.1.5 on 2021-02-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210218_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tax',
            new_name='GSD',
        ),
    ]
