# Generated by Django 3.1.5 on 2021-02-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210218_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='appointment_date',
            field=models.DateField(blank=True, default='mm/dd/yyyy', null=True),
        ),
    ]
